{ ... }:
{
  imports = [
    ./alacritty
    ./awesome
    ./base
    ./copyq
    ./eww
    ./firefox
    ./fish
    ./gitnuro
    ./hyprland
    ./jetbrains
    ./picom
    ./rofi
    ./sddm-sugar-candy
    ./starship
    ./swaylock-effects
    ./vim
    ./swaync
    ./vscodium
    ./bluetooth.nix
    ./devtools.nix
    ./fastfetch.nix
    ./nautilus.nix
    ./nvidia.nix
    ./onedrive.nix
    ./piper.nix
    ./playerctl.nix
    ./steam.nix
    ./virt-manager.nix
    ./wsl-vpnkit.nix
  ];
}