hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1200@120",
    position = "0x0",
    scale    = 1,
})
--hl.monitor({
--    output   = "eDP-1",
--    mode     = "2880x1800@120",
--    position = "0x0",
--    scale    = 1.5,
--})

-- mirror to unconfigured monitors
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
    mirror = "eDP-1",
})

-- override with config generated by nwg-displays
require("monitors")

hl.config({
    input = {
        touchpad = {
            scroll_factor = 0.2,
            natural_scroll = true,
        },
    },
})

-- fix flameshot
hl.window_rule({
    match = {
        initial_title = "flameshot",
    },
    size = {"monitor_w", "monitor_h"},
})

-- adjust keyboard backlight brightness (holdable)
hl.bind("SUPER + CTRL + SHIFT + down", hl.dsp.exec_cmd("brightnessctl -d platform::kbd_backlight s 1-"), { repeating = true})
hl.bind("SUPER + CTRL + SHIFT + up", hl.dsp.exec_cmd("brightnessctl -d platform::kbd_backlight s 1+"), { repeating = true })

-- toggle mirroring to TV
hl.bind("SUPER + CTRL + SHIFT + P", hl.dsp.exec_cmd("sh -c '[ -s ~/.config/hypr/monitors.lua ] && reset-monitors && brightnessctl s 30% || /etc/dotfiles/devices/laptop/mirror-tv.sh'"))

---- copilot key
hl.window_rule({
    match = {
        initial_class = "qimgv",
        initial_title = ".*copilot\\..*",
    },
    fullscreen = true,
    no_anim = true,
    float = true,
})
-- show fullscreen image only holding button 
hl.bind(       "SUPER + SHIFT + code:201", hl.dsp.exec_cmd("qimgv /etc/dotfiles/devices/laptop/copilot.jpg"))
hl.bind("CTRL + SUPER + SHIFT + code:201", hl.dsp.exec_cmd("qimgv /etc/dotfiles/devices/laptop/copilot.jpeg"))
hl.bind(       "SUPER + SHIFT + code:201", hl.dsp.exec_cmd("pkill qimgv"), { repeating = true })
hl.bind("CTRL + SUPER + SHIFT + code:201", hl.dsp.exec_cmd("pkill qimgv"), { repeating = true })
-- open fullscreen video: vlc --fullscreen --loop --no-video-title-show /etc/dotfiles/devices/laptop/copilot.mp4
