#!/bin/sh

set_sink() {
  # set $1 as default sink with 100% volume using wireplumber id
  id=$(wpctl status | sed -n '/Sinks:/,/Sources:/{/Sinks:/d;/Sources:/d;p}' | grep -Fm 1 "$1" | sed "s/[^0-9]*\([0-9]\{2,\}\).*/\1/")
  if [ -z "$id" ]; then
    echo "couldnt get id for sink '$1'"
    return
  fi
  wpctl set-default $id
  wpctl set-volume $id 100%
}

# use TV speakers
set_sink "Radeon High Definition Audio Controller [Rembrandt/Strix] HDMI / DisplayPort 2 Output" &

# reduce integrated monitor brightness
brightnessctl s 5%

cat <<EOF > ~/.config/hypr/monitors.lua
-- generated by mirror-tv.sh
hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@120",
    position = "0x0",
    scale    = 1,
})
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "2560x1440@59.95",
    position = "0x1431",
    scale    = 1,
    mirror   = "eDP-1",
})
EOF
# to register monitor config change
hyprctl reload
# fix wallpaper / borders
python /etc/dotfiles/modules/hyprland/wallpaper.py
